baseURL = "https://jerryliucn.github.io/"



# 更改使用 Hugo 构建网站时使用的默认主题

theme = "LoveIt"



# 网站标题

title = "我的全新 Hugo 网站"



# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]

languageCode = "zh-CN"

# 语言名称 ["English", "简体中文", "Français", "Polski", ...]

languageName = "简体中文"

# 是否包括中日韩文字

hasCJKLanguage = true



# 菜单配置

[menu]

  [[menu.main]]

    weight = 1

    identifier = "posts"

    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标

    pre = ""

    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标

    post = ""

    name = "文章"

    url = "/posts/"

    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题

    title = ""

  [[menu.main]]

    weight = 2

    identifier = "tags"

    pre = ""

    post = ""

    name = "标签"

    url = "/tags/"

    title = ""

  [[menu.main]]

    weight = 3

    identifier = "categories"

    pre = ""

    post = ""

    name = "分类"

    url = "/categories/"

    title = ""



# Hugo 解析文档的配置

[markup]

  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)

  [markup.highlight]

    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)

    noClasses = false

[params.author]
	name = "Jerry Liu CN"
	email = ""
	link = ""
[params.search]
	enable = false
	# type of search engine ["lunr", "algolia"]
	# 搜索引擎的类型 ["lunr", "algolia"]
	type = "algolia"
	# max index length of the chunked content
	# 文章内容最长索引长度
	contentLength = 4000
	# placeholder of the search bar
	# 搜索框的占位提示语
	placeholder = ""
	# max number of results length
	# 最大结果数目
	maxResultLength = 10
	# snippet length of the result
	# 结果内容片段长度
	snippetLength = 30
	# HTML tag name of the highlight part in results
	# 搜索结果中高亮部分的 HTML 标签
	highlightTag = "em"
	# whether to use the absolute URL based on the baseURL in search index
	# 是否在搜索索引中使用基于 baseURL 的绝对路径
	absoluteURL = false
	[params.search.algolia]
		index = "jerryliucn.github.io"
		appID = "YYG96ZVJZO"
		searchKey = "b702a3cc1822393de89081d6403273c1"
[outputs]
	home = ["HTML", "RSS", "JSON"]