baseURL = "https://jerryliucn.github.io/"
theme = "LoveIt"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    weight = 1
    title = "Jerry Liu CN's Blog"
    languageCode = "en"
    languageName = "English"
    contentDir = "content/en"
    hasCJKLanguage = false
    [languages.en.params]
      [languages.en.params.header.title]
        name = "Jerry Liu CN's Blog"
      [languages.en.params.home.profile]
        subtitle = "Do not grieve for the past, nor yearn for the future. If you live in the present, your mind will be clear and joyful."
      [languages.en.params.search.algolia]
        index = "jerryliucn-github-io-en"
        appID = "YYG96ZVJZO"
        searchKey = "b702a3cc1822393de89081d6403273c1"
    [[languages.en.menu.main]]
      weight = 1
      name = "Posts"
      url = "/posts/"
    [[languages.en.menu.main]]
      weight = 2
      name = "Tags"
      url = "/tags/"
    [[languages.en.menu.main]]
      weight = 3
      name = "Categories"
      url = "/categories/"

  [languages.zh-cn]
    weight = 2
    title = "Jerry Liu CN 的博客"
    languageCode = "zh-CN"
    languageName = "简体中文"
    contentDir = "content/zh-cn"
    hasCJKLanguage = true
    [languages.zh-cn.params]
      [languages.zh-cn.params.header.title]
        name = "Jerry Liu CN's 博客"
      [languages.zh-cn.params.home.profile]
        subtitle = "不悲过去事，未来勿憧憬，若持身现在，颜色即朗悦。"
      [languages.zh-cn.params.search.algolia]
        index = "jerryliucn-github-io-zh"
        appID = "YYG96ZVJZO"
        searchKey = "b702a3cc1822393de89081d6403273c1"
    [[languages.zh-cn.menu.main]]
      weight = 1
      name = "文章"
      url = "/posts/"
    [[languages.zh-cn.menu.main]]
      weight = 2
      name = "标签"
      url = "/tags/"
    [[languages.zh-cn.menu.main]]
      weight = 3
      name = "分类"
      url = "/categories/"

[params]
  mainSections = ["posts"]

[params.author]
  name = "Jerry Liu CN"
  email = "liuyuwei1989@yeah.net"
  link = "https://jerryliucn.github.io/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "algolia"
  isPlainText = true
  notAlternative = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params.page.comment]
  enable = true
  type = "giscus"

[params.page.comment.giscus]
  repo = "jerryliucn/jerryliucn.github.io"
  repoID = "R_kgDOO7oqFQ"
  category = "General"
  categoryID = "DIC_kwDOO7oqFc4Crhid"
  mapping = "pathname"
  strict = 0
  reactionsEnabled = 1
  emitMetadata = 1
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"
  loading = "lazy"