name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 你的源码分支

jobs:
  build-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download Hugo extended
        run: |
          Invoke-WebRequest -Uri "https://github.com/gohugoio/hugo/releases/download/v0.147.8/hugo_extended_withdeploy_0.147.8_windows-amd64.zip" -OutFile "hugo.zip"
          Expand-Archive -Path "hugo.zip" -DestinationPath "."
          $env:Path = "$PWD" + ";" + $env:Path
          hugo version

      - name: Clean public directory
        run: |
          if (Test-Path public) { Remove-Item -Recurse -Force public/* }

      - name: Build with Hugo (production)
        run: hugo --environment production

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install algolia-uploader
        run: npm install -D algolia-uploader

      - name: Create .env for zh Algolia index
        run: |
          Add-Content .env "ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }}"
          Add-Content .env "ALGOLIA_ADMIN_API_KEY=${{ secrets.ALGOLIA_ADMIN_API_KEY }}"
          Add-Content .env "ALGOLIA_INDEX_NAME=${{ secrets.ALGOLIA_INDEX_NAME_ZH }}"
          Add-Content .env "DATA_DIR=public/zh-cn"

      - name: Upload zh Algolia index
        run: npx algolia-uploader

      - name: Clean .env before creating for en Algolia index
        run: |
          if (Test-Path .env) { Remove-Item .env }

      - name: Create .env for en Algolia index
        run: |
          Add-Content .env "ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }}"
          Add-Content .env "ALGOLIA_ADMIN_API_KEY=${{ secrets.ALGOLIA_ADMIN_API_KEY }}"
          Add-Content .env "ALGOLIA_INDEX_NAME=${{ secrets.ALGOLIA_INDEX_NAME_EN }}"
          Add-Content .env "DATA_DIR=public/en"

      - name: Upload en Algolia index
        run: npx algolia-uploader

      - name: Show public directory structure
        run: |
          Write-Output "Public directory structure:"
          tree public

      - name: Show zh-cn post index.html
        run: |
          Write-Output "public/zh-cn/posts/hugo-algolia-search/index.html content:"
          Get-Content public/zh-cn/posts/hugo-algolia-search/index.html

      - name: Build with Hugo (production)
        run: hugo --environment production

      - name: Show LoveIt theme directory structure
        run: |
          Write-Output "themes/LoveIt directory structure:"
          tree themes/LoveIt || find themes/LoveIt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: jerryliucn/jerryliucn.github.io
          publish_dir: ./public
          publish_branch: main
